# Generated by Django 5.0.4 on 2026-08-05 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("NOTIFICATION_CREATED", "Notification Created"),
                            ("NOTIFICATION_SENT", "Notification Sent"),
                            ("NOTIFICATION_FAILED", "Notification Failed"),
                            ("API_KEY_CREATED", "API Key Created"),
                            ("API_KEY_REVOKED", "API Key Revoked"),
                            ("PROVIDER_CONFIGURED", "Provider Configured"),
                            ("TEMPLATE_CREATED", "Template Created"),
                            ("TEMPLATE_UPDATED", "Template Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.apikey",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "action"],
                        name="audit_logs_organiz_9c5b7f_idx",
                    ),
                    models.Index(
                        fields=["organization", "created_at"],
                        name="audit_logs_organiz_af0d8d_idx",
                    ),
                ],
            },
        ),
    ]
